// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using justaddgelang_web_api.Models;

#nullable disable

namespace justaddgelang_web_api.Migrations
{
    [DbContext(typeof(dbcontext))]
    [Migration("20250406231409_migration6")]
    partial class migration6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("justaddgelang_web_api.Models.cart", b =>
                {
                    b.Property<int>("cart_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cart_id"));

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("cart_id");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.cart_items", b =>
                {
                    b.Property<int>("cart_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cart_item_id"));

                    b.Property<int>("cart_id")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("cart_item_id");

                    b.ToTable("cart_items");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.HasKey("category_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.order_items", b =>
                {
                    b.Property<int?>("order_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("order_item_id"));

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("order_item_id");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.orders", b =>
                {
                    b.Property<int?>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("order_id"));

                    b.Property<int>("address_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("order_date")
                        .HasColumnType("timestamp")
                        .HasColumnName("order_date");

                    b.Property<string>("recipient_name")
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<string>("recipient_number")
                        .HasColumnType("text")
                        .HasColumnName("recipient_number");

                    b.Property<string>("status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("order_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.payment", b =>
                {
                    b.Property<int?>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("payment_id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("timestamp")
                        .HasColumnName("payment_date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("payment_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.product", b =>
                {
                    b.Property<int?>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("product_id"));

                    b.Property<int>("category_id")
                        .HasColumnType("integer");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("product_picture")
                        .HasColumnType("text")
                        .HasColumnName("product_picture");

                    b.Property<decimal>("product_price")
                        .HasColumnType("numeric")
                        .HasColumnName("product_price");

                    b.Property<int>("product_stock")
                        .HasColumnType("int")
                        .HasColumnName("product_stock");

                    b.HasKey("product_id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.reviews", b =>
                {
                    b.Property<int?>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("review_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("review_text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("review_id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.user_address", b =>
                {
                    b.Property<int?>("address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("address_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("address_type")
                        .HasColumnType("text")
                        .HasColumnName("address_type");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("pincode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pincode");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("address_id");

                    b.ToTable("user_addresses");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.users", b =>
                {
                    b.Property<int?>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("user_id"));

                    b.Property<string>("email_id")
                        .HasColumnType("text")
                        .HasColumnName("email_id");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("phone_no")
                        .HasColumnType("text")
                        .HasColumnName("phone_no");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("usertype")
                        .HasColumnType("text")
                        .HasColumnName("usertype");

                    b.HasKey("user_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("justaddgelang_web_api.Models.wishlist", b =>
                {
                    b.Property<int?>("wishlist_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("wishlist_id"));

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("wishlist_id");

                    b.ToTable("wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
